### ISSUE TITLE
Build an Application End-to-End Using CAP, Node.js and VS Code

### ISSUE THREAD

**Issue by ValterAraujoJr** [sap-tutorials/Tutorials#18924]
Mission: https://developers.sap.com/mission.btp-application-cap-e2e.html
--------------------------

Hello there! First congratulation on this tutorial, it is very detailed and clear.
I finished the whole mission; however, I was not able to run the application from BTP, it seems all components are on and running, security in place, but the OData service is not available. Please see screenshot below:
![image](https://user-images.githubusercontent.com/32312757/196543040-6d3757e8-53f2-4c67-8b4c-0af75f7f85f3.png)

My environment is:
@sap/cds: 6.2.1
@sap/cds-compiler: 3.3.2
@sap/cds-dk: 6.2.1
@sap/cds-dk (global): 6.2.1
@sap/cds-foss: 4.0.0
@sap/cds-mtx: -- missing --
@sap/xssec: 3.2.14
Node.js: v16.18.0

Could you please guide me how to troubleshoot it?

Thank you in advance.
Valter

**Comment by ValterAraujoJr** [comment]
Hi @manjuX,

I re-checked the destination configuration as you mentioned, and I was able to see a difference in this line:
it was URL: `~{srv-api/srv-url}`
now it is URL: `'~{srv-api/srv-url}'`

Interesting that I never typed anything from this tutorial, I always copy and paste.
After that I built it again and re-deploy it. Unfortunately, the error persists.

Attached is the log from today and the mta.yaml file.
[cpapp-srv-2022-10-19 19_20_12.152+0000.txt](https://github.com/sap-tutorials/Tutorials/files/9823610/cpapp-srv-2022-10-19.19_20_12.152%2B0000.txt)

I had to zip it to be accepted here:
[mta.zip](https://github.com/sap-tutorials/Tutorials/files/9823615/mta.zip)

Thank you for your help.
Valter

**Comment by manjuX** [comment]
Hi @ValterAraujoJr,

The logs indicate an issue with the DB connectivity, can you check if your DB is running without issue? It automatically stops if it is inactive.

Best regards,
Manju

**Comment by ValterAraujoJr** [comment]
Hi @manjuX,

All tests since day 1 were performed with the DB running.
I did another test today, starting first the DB and after the app, the issue persists. 
Log is attached:
[cpapp-srv-2022-10-24 23_28_06.567+0000.txt](https://github.com/sap-tutorials/Tutorials/files/9855976/cpapp-srv-2022-10-24.23_28_06.567%2B0000.txt)


![Risks_ServiceIssuesOct24](https://user-images.githubusercontent.com/32312757/197649162-4ea27399-623c-4e83-bc7d-b491eae9b26f.png)

Please let me know the next steps.

Thank you for your help.
Valter

**Comment by rcaziraghi** [comment]
Hello @ValterAraujoJr ,

I was comparing your MTA file with mine (back when I did this tutorial some time ago) and I noticed two differences that may have affected your outcome.

Firstly in my modules, I have the "cpapp-uaa" added to the "cpapp-db-deployer" required tag:

```
- name: cpapp-db-deployer
  type: hdb
  path: gen/db
  requires:
  - name: cpapp-db
  - name: cpapp-uaa
  - name: cpapp-logs
  parameters:
    buildpack: nodejs_buildpack
```

And secondly, on the "cpapp-db" resource, I have an additional property:

```
- name: cpapp-db
  type: com.sap.xs.hdi-container
  parameters:
    service: hana
    service-plan: hdi-shared
  properties:
    hdi-service-name: ${service-name}
```

As I said, I did this tutorial some time ago and maybe these changes are not valid, but I can confirm that it worked at the time.

Please let me know if it was of any help.

Thank you.
